In [1]:
import numpy as np   

from sklearn.linear_model import LinearRegression

import pandas as pd    

import matplotlib.pyplot as plt   
import matplotlib.style
plt.style.use('classic')
import seaborn as sns

In [2]:
mpg_df = pd.read_csv("car-mpg.csv")

In [3]:
mpg_df

mpg  cyl   disp   hp    wt   acc  yr  origin  car_type  \
0    18.0    8  307.0  130  3504  12.0  70       1         0   
1    15.0    8  350.0  165  3693  11.5  70       1         0   
2    18.0    8  318.0  150  3436  11.0  70       1         0   
3    16.0    8  304.0  150  3433  12.0  70       1         0   
4    17.0    8  302.0  140  3449  10.5  70       1         0   
..    ...  ...    ...  ...   ...   ...  ..     ...       ...   
393  27.0    4  140.0   86  2790  15.6  82       1         1   
394  44.0    4   97.0   52  2130  24.6  82       2         1   
395  32.0    4  135.0   84  2295  11.6  82       1         1   
396  28.0    4  120.0   79  2625  18.6  82       1         1   
397  31.0    4  119.0   82  2720  19.4  82       1         1   

                      car_name  
0    chevrolet chevelle malibu  
1            buick skylark 320  
2           plymouth satellite  
3                amc rebel sst  
4                  ford torino  
..                         ...  
393            ford mustang gl  
394                  vw pickup  
395              dodge rampage  
396                ford ranger  
397                 chevy s-10  

[398 rows x 10 columns]

In [4]:
mpg_df.isnull().sum()

mpg         0
cyl         0
disp        0
hp          0
wt          0
acc         0
yr          0
origin      0
car_type    0
car_name    0
dtype: int64

In [5]:
mpg_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64  
 2   disp      398 non-null    float64
 3   hp        398 non-null    object 
 4   wt        398 non-null    int64  
 5   acc       398 non-null    float64
 6   yr        398 non-null    int64  
 7   origin    398 non-null    int64  
 8   car_type  398 non-null    int64  
 9   car_name  398 non-null    object 
dtypes: float64(3), int64(5), object(2)
memory usage: 31.2+ KB


In [6]:
mpg_df['hp'] = pd.to_numeric(mpg_df['hp'], errors='coerce')

In [7]:
mpg_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64  
 2   disp      398 non-null    float64
 3   hp        392 non-null    float64
 4   wt        398 non-null    int64  
 5   acc       398 non-null    float64
 6   yr        398 non-null    int64  
 7   origin    398 non-null    int64  
 8   car_type  398 non-null    int64  
 9   car_name  398 non-null    object 
dtypes: float64(4), int64(5), object(1)
memory usage: 31.2+ KB


In [8]:
mpg_df['hp'] = mpg_df['hp'].fillna(mpg_df['hp'].mean())

In [9]:
mpg_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64  
 2   disp      398 non-null    float64
 3   hp        398 non-null    float64
 4   wt        398 non-null    int64  
 5   acc       398 non-null    float64
 6   yr        398 non-null    int64  
 7   origin    398 non-null    int64  
 8   car_type  398 non-null    int64  
 9   car_name  398 non-null    object 
dtypes: float64(4), int64(5), object(1)
memory usage: 31.2+ KB


In [10]:
mpg_df.isnull().sum()

mpg         0
cyl         0
disp        0
hp          0
wt          0
acc         0
yr          0
origin      0
car_type    0
car_name    0
dtype: int64

In [11]:
X = mpg_df.drop(['mpg','origin','car_type','car_name'],axis=1)

In [12]:
Y = mpg_df['mpg']

##BUILDING A LINEAR REGRESSION

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size = 0.30 , random_state=1)

In [15]:
Lin_Reg = LinearRegression()

In [16]:
Line = Lin_Reg.fit(X_train,Y_train)

In [17]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 278 entries, 350 to 37
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   cyl     278 non-null    int64  
 1   disp    278 non-null    float64
 2   hp      278 non-null    float64
 3   wt      278 non-null    int64  
 4   acc     278 non-null    float64
 5   yr      278 non-null    int64  
dtypes: float64(3), int64(3)
memory usage: 15.2 KB


In [18]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 174 to 247
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   cyl     120 non-null    int64  
 1   disp    120 non-null    float64
 2   hp      120 non-null    float64
 3   wt      120 non-null    int64  
 4   acc     120 non-null    float64
 5   yr      120 non-null    int64  
dtypes: float64(3), int64(3)
memory usage: 6.6 KB


In [19]:
Line.intercept_

-15.536613116761533

In [20]:
Line.coef_

array([-0.18121006,  0.0110253 , -0.00964325, -0.0071721 ,  0.02649411,
        0.7879939 ])

In [21]:
for idx, col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {Lin_Reg.coef_[idx]}")


The coefficient for cyl is -0.18121005727478962
The coefficient for disp is 0.011025296788744438
The coefficient for hp is -0.009643252987610923
The coefficient for wt is -0.007172102123643265
The coefficient for acc is 0.02649411326151786
The coefficient for yr is 0.7879939031727107


In [22]:
##MODEL EVALUATION

In [23]:
Line.score(X_train,Y_train) ## for train data

0.7997247899128472

In [24]:
Line.score(X_test,Y_test) ## for test data

0.8265574169791732

In [25]:
## MEAN SQUARE ERROR
mse = np.mean((Line.predict(X_test) - Y_test) ** 2)

In [26]:
mse

10.140657383994672

In [27]:
Y_pred = Line.predict(X_test)

In [28]:
Y_pred

array([22.40821139, 25.72374947, 20.1951407 , 25.59612726, 24.3829004 ,
       15.41537338, 28.66562291, 33.70496135, 17.04814249, 10.72421866,
       31.34677648, 16.87970984, 22.47018007, 26.37903941, 35.73845387,
       22.4894354 , 10.12461369, 21.14386719,  8.14618217, 32.32144447,
       25.41210419, 31.20164378, 21.79076023, 25.01454842, 26.56969495,
       28.45874297, 31.624202  , 31.83795818, 15.69447182, 31.03109439,
       28.23911019, 10.0683631 , 20.10912327, 27.77898681, 26.00263674,
       13.64735073, 28.24060091,  8.16639711, 32.87978587, 25.08930939,
       25.98012469, 25.75883487, 20.98982548, 32.67942101, 27.40314547,
       22.55085479, 21.08467065, 11.68134947, 28.03757131, 19.24612194,
       24.22655452, 27.78509293, 16.59688051, 11.93604846, 30.23331078,
       24.69701246,  9.53640926, 12.87454272, 30.06612251, 35.0154818 ,
       35.00269988, 35.03402768, 18.15710098, 28.84009875, 19.87418478,
       32.13812728, 28.11382561, 27.06650263, 30.80185792, 12.59

In [29]:
X_train.columns

Index(['cyl', 'disp', 'hp', 'wt', 'acc', 'yr'], dtype='object')

In [30]:
X_train['yr'].mean()

75.82374100719424

In [31]:
data = {'cyl' : [10,8,12] , 'disp' : [223,339,200] , 'hp' :[113,150,210] , 'wt' : [2400,2500,2350] , 'acc' : [15,16,20],'yr' : [90,70,72]}

In [32]:
X_sample = pd.DataFrame(data)

In [33]:
Y_Sample_Pred = Line.predict(X_sample)

In [34]:
Y_Sample_Pred

array([38.12405779, 22.95801781, 22.87984573])

In [35]:
from scipy.stats import zscore 
X_train_scaled = X_train.apply(zscore)

In [36]:
X_test_scaled = X_test.apply(zscore, axis=0)  # Scale each column (feature) independently
Y_train_scaled = zscore(Y_train)  # If Y_train is a Series
Y_test_scaled = zscore(Y_test)    


In [37]:
Lin_reg = LinearRegression()
Line2 = Lin_reg.fit(X_train_scaled, Y_train_scaled)

In [38]:
Line2.score(X_train_scaled , Y_train_scaled)

0.7997247899128471

In [39]:
Line2.score(X_test_scaled , Y_test_scaled)

0.8290280290108031

## RIDGE LINEAR REGRESSION 


In [40]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso


In [41]:
ridge = Ridge(alpha=0.000000000004)
ridge.fit(X_train_scaled, Y_train_scaled)
print("Ridge Model Coefficients:", ridge.coef_)

Ridge Model Coefficients: [-0.03847864  0.14301483 -0.04595239 -0.76936874  0.00933427  0.36930094]


In [42]:
ridge.score(X_test_scaled , Y_test_scaled)

0.8290280290108049

In [43]:
ridge.score(X_train_scaled , Y_train_scaled)

0.7997247899128472

In [44]:
ridge.score(X_train , Y_train)

-87582.68478526546

In [45]:
ridge.score(X_test , Y_test)

-96825.10344611052

In [46]:
ridge = Ridge(alpha=0.3)
ridge.fit(X_train, Y_train)
print("Ridge Model Coefficients:", ridge.coef_)

Ridge Model Coefficients: [-0.18042647  0.01101165 -0.00964852 -0.00717187  0.02646778  0.78792163]


In [47]:
ridge.score(X_train,Y_train)

0.7997247864457854

##LASSSO REGULARIZATION

In [48]:
lasso = Lasso(alpha=0.007)
lasso.fit(X_train_scaled, Y_train_scaled)
print("Lasso Model Coefficients:", lasso.coef_)

Lasso Model Coefficients: [-0.          0.         -0.02845925 -0.68514049  0.          0.35835042]


In [49]:
lasso.score(X_test_scaled , Y_test_scaled)

0.8316018661905034

In [50]:
lasso.score(X_train_scaled , Y_train_scaled)

0.7984528879088575